### ISSUE TITLE
Request for Inclusion in Puzzle Hunt Toolbox

### ISSUE THREAD

**Issue by SAMFYB** [dariusk/ea-thesaurus#1]
Hi,

I'm collecting tools that might help solving puzzle hunt problems, here -> [puzzle-hunter-toolbox](https://github.com/SAMFYB/puzzle-hunter-toolbox).

Would you mind if I include this repository in the list and link here?

Thanks,
Sam

**Comment by dariusk** [comment]
Please feel free to include it!!

**Comment by SAMFYB** [comment]
Thanks!
